### ISSUE TITLE
Dependencies issue on CREATE following installation instructions

### ISSUE THREAD

**Issue by JoniColeman** [opain/GenoPred#117]
Hi Ollie,

Following the installation instructions, installation fails at the dependencies stage as follows:

(genopred) k1204688@erc-hpc-comp186:~/sgdp_coleman/Software/GenoPred/pipeline$ snakemake -j 1 --use-conda --conda-frontend mamba install_r_packages
Building DAG of jobs...
Traceback (most recent call last):
  File "/users/k1204688/.conda/envs/genopred/lib/python3.8/site-packages/conda/exception_handler.py", line 17, in __call__
    return func(*args, **kwargs)
  File "/users/k1204688/.conda/envs/genopred/lib/python3.8/site-packages/conda/cli/main.py", line 51, in main_subshell
    from .conda_argparse import do_call, generate_parser, generate_pre_parser
  File "/users/k1204688/.conda/envs/genopred/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 50, in <module>
    from .main_create import configure_parser as configure_parser_create
  File "/users/k1204688/.conda/envs/genopred/lib/python3.8/site-packages/conda/cli/main_create.py", line 11, in <module>
    from ..notices import notices
  File "/users/k1204688/.conda/envs/genopred/lib/python3.8/site-packages/conda/notices/__init__.py", line 3, in <module>
    from .core import notices  # noqa: F401
  File "/users/k1204688/.conda/envs/genopred/lib/python3.8/site-packages/conda/notices/core.py", line 14, in <module>
    from . import cache, fetch, views
  File "/users/k1204688/.conda/envs/genopred/lib/python3.8/site-packages/conda/notices/cache.py", line 25, in <module>
    from ..utils import ensure_dir_exists
  File "/users/k1204688/.conda/envs/genopred/lib/python3.8/site-packages/conda/utils.py", line 23, in <module>
    from .gateways.disk.read import compute_sum
  File "/users/k1204688/.conda/envs/genopred/lib/python3.8/site-packages/conda/gateways/disk/read.py", line 31, in <module>
    from ...exceptions import CondaUpgradeError, CondaVerificationError, PathNotFoundError
  File "/users/k1204688/.conda/envs/genopred/lib/python3.8/site-packages/conda/exceptions.py", line 16, in <module>
    from requests.exceptions import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError' from 'requests.exceptions' (/users/k1204688/.local/lib/python3.8/site-packages/requests/exceptions.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/k1204688/.conda/envs/genopred/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/users/k1204688/.conda/envs/genopred/lib/python3.8/site-packages/conda/cli/main.py", line 128, in main
    return conda_exception_handler(main, *args, **kwargs)
  File "/users/k1204688/.conda/envs/genopred/lib/python3.8/site-packages/conda/exception_handler.py", line 388, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/users/k1204688/.conda/envs/genopred/lib/python3.8/site-packages/conda/exception_handler.py", line 20, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/users/k1204688/.conda/envs/genopred/lib/python3.8/site-packages/conda/exception_handler.py", line 51, in handle_exception
    from .exceptions import (
  File "/users/k1204688/.conda/envs/genopred/lib/python3.8/site-packages/conda/exceptions.py", line 16, in <module>
    from requests.exceptions import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError' from 'requests.exceptions' (/users/k1204688/.local/lib/python3.8/site-packages/requests/exceptions.py)
Traceback (most recent call last):
  File "/users/k1204688/.local/lib/python3.8/site-packages/snakemake/__init__.py", line 726, in snakemake
    success = workflow.execute(
  File "/users/k1204688/.local/lib/python3.8/site-packages/snakemake/workflow.py", line 978, in execute
    dag.create_conda_envs(
  File "/users/k1204688/.local/lib/python3.8/site-packages/snakemake/dag.py", line 313, in create_conda_envs
    env.create(dryrun)
  File "/users/k1204688/.local/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 391, in create
    pin_file = self.pin_file
  File "/users/k1204688/.local/lib/python3.8/site-packages/snakemake/common/__init__.py", line 192, in __get__
    value = self.method(instance)
  File "/users/k1204688/.local/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 107, in pin_file
    f".{self.conda.platform}.pin.txt"
  File "/users/k1204688/.local/lib/python3.8/site-packages/snakemake/common/__init__.py", line 192, in __get__
    value = self.method(instance)
  File "/users/k1204688/.local/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 102, in conda
    return Conda(self._container_img)
  File "/users/k1204688/.local/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 648, in __init__
    shell.check_output(
  File "/users/k1204688/.local/lib/python3.8/site-packages/snakemake/shell.py", line 63, in check_output
    return sp.check_output(cmd, shell=True, executable=executable, **kwargs)
  File "/users/k1204688/.conda/envs/genopred/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/users/k1204688/.conda/envs/genopred/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'conda info --json' returned non-zero exit status 1.

Not really clear to me why this happens – I'll find a work-around on CREATE and report back, but wanted to flag this as a bug to be solved. I think other answers here may solve this - I will check that.

**Comment by JoniColeman** [comment]
This is a known issue with certain versions of python. It can be resolved by running:
```
export PYTHONNOUSERSITE=True
```
and then running the command.
